<?xml version="1.0" encoding="utf-8"?><Database Name="ESEMKA_EXAMINATION" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-DENT5RFJ;Initial Catalog=ESEMKA_EXAMINATION;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Esemka_Examination_V2.Properties.Settings" SettingsPropertyName="ESEMKA_EXAMINATIONConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cases" Member="cases">
    <Type Name="case">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="creator_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="number_of_questions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="case_cases_detail" Member="cases_details" ThisKey="id" OtherKey="case_id" Type="cases_detail" />
      <Association Name="case_schedule" Member="schedules" ThisKey="id" OtherKey="case_id" Type="schedule" />
      <Association Name="user_case" Member="user" ThisKey="creator_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cases_details" Member="cases_details">
    <Type Name="cases_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="option_a" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="option_b" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="option_c" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="option_d" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="correct_answer" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="case_cases_detail" Member="case" ThisKey="case_id" OtherKey="id" Type="case" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="role_user" Member="users" ThisKey="id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Table Name="dbo.rooms" Member="rooms">
    <Type Name="room">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="imagePath" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="room_schedule" Member="schedules" ThisKey="id" OtherKey="room_id" Type="schedule" />
    </Type>
  </Table>
  <Table Name="dbo.schedules" Member="schedules">
    <Type Name="schedule">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="examiner_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="room_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="schedule_schedules_participant" Member="schedules_participants" ThisKey="id" OtherKey="schedule_id" Type="schedules_participant" />
      <Association Name="case_schedule" Member="case" ThisKey="case_id" OtherKey="id" Type="case" IsForeignKey="true" />
      <Association Name="room_schedule" Member="room" ThisKey="room_id" OtherKey="id" Type="room" IsForeignKey="true" />
      <Association Name="type_schedule" Member="type" ThisKey="type_id" OtherKey="id" Type="type" IsForeignKey="true" />
      <Association Name="user_schedule" Member="user" ThisKey="examiner_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.schedules_participants" Member="schedules_participants">
    <Type Name="schedules_participant">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="participant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="schedule_schedules_participant" Member="schedule" ThisKey="schedule_id" OtherKey="id" Type="schedule" IsForeignKey="true" />
      <Association Name="user_schedules_participant" Member="user" ThisKey="participant_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.types" Member="types">
    <Type Name="type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="type_schedule" Member="schedules" ThisKey="id" OtherKey="type_id" Type="schedule" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="user_case" Member="cases" ThisKey="id" OtherKey="creator_id" Type="case" />
      <Association Name="user_schedule" Member="schedules" ThisKey="id" OtherKey="examiner_id" Type="schedule" />
      <Association Name="user_schedules_participant" Member="schedules_participants" ThisKey="id" OtherKey="participant_id" Type="schedules_participant" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>