namespace Esemka_Examination_V2
{
    partial class FormViewCase
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormViewCase));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dgvData = new System.Windows.Forms.DataGridView();
            this.tbSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.tbQuestion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblQuestion = new System.Windows.Forms.Label();
            this.tbAnswerA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.tbAnswerB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.tbAnswerD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.tbAnswerC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cboAnswer = new System.Windows.Forms.ComboBox();
            this.label8 = new System.Windows.Forms.Label();
            this.btnFirst = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPrev = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLast = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvData
            // 
            this.dgvData.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvData.BackgroundColor = System.Drawing.Color.White;
            this.dgvData.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.dgvData.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvData.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvData.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvData.Location = new System.Drawing.Point(43, 150);
            this.dgvData.Name = "dgvData";
            this.dgvData.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dgvData.RowHeadersWidth = 51;
            this.dgvData.RowTemplate.Height = 30;
            this.dgvData.Size = new System.Drawing.Size(915, 131);
            this.dgvData.TabIndex = 68;
            this.dgvData.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvData_CellClick);
            // 
            // tbSearch
            // 
            this.tbSearch.AcceptsReturn = false;
            this.tbSearch.AcceptsTab = false;
            this.tbSearch.AnimationSpeed = 200;
            this.tbSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSearch.AutoSizeHeight = true;
            this.tbSearch.BackColor = System.Drawing.Color.Transparent;
            this.tbSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSearch.BackgroundImage")));
            this.tbSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSearch.BorderRadius = 15;
            this.tbSearch.BorderThickness = 1;
            this.tbSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbSearch.DefaultText = "";
            this.tbSearch.FillColor = System.Drawing.Color.White;
            this.tbSearch.HideSelection = true;
            this.tbSearch.IconLeft = null;
            this.tbSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.IconPadding = 12;
            this.tbSearch.IconRight = ((System.Drawing.Image)(resources.GetObject("tbSearch.IconRight")));
            this.tbSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.Lines = new string[0];
            this.tbSearch.Location = new System.Drawing.Point(688, 81);
            this.tbSearch.MaxLength = 32767;
            this.tbSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSearch.Modified = false;
            this.tbSearch.Multiline = false;
            this.tbSearch.Name = "tbSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnIdleState = stateProperties4;
            this.tbSearch.Padding = new System.Windows.Forms.Padding(3);
            this.tbSearch.PasswordChar = '\0';
            this.tbSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSearch.PlaceholderText = "Write name...";
            this.tbSearch.ReadOnly = false;
            this.tbSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSearch.SelectedText = "";
            this.tbSearch.SelectionLength = 0;
            this.tbSearch.SelectionStart = 0;
            this.tbSearch.ShortcutsEnabled = true;
            this.tbSearch.Size = new System.Drawing.Size(270, 45);
            this.tbSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSearch.TabIndex = 63;
            this.tbSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSearch.TextMarginBottom = 0;
            this.tbSearch.TextMarginLeft = 5;
            this.tbSearch.TextMarginTop = 1;
            this.tbSearch.TextPlaceholder = "Write name...";
            this.tbSearch.UseSystemPasswordChar = false;
            this.tbSearch.WordWrap = true;
            this.tbSearch.TextChanged += new System.EventHandler(this.tbSearch_TextChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label3.Location = new System.Drawing.Point(535, 93);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(148, 26);
            this.label3.TabIndex = 62;
            this.label3.Text = "Search by creator";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Poppins", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(391, 29);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(170, 50);
            this.label1.TabIndex = 61;
            this.label1.Text = "View Case";
            // 
            // tbQuestion
            // 
            this.tbQuestion.AcceptsReturn = false;
            this.tbQuestion.AcceptsTab = false;
            this.tbQuestion.AnimationSpeed = 200;
            this.tbQuestion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbQuestion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbQuestion.AutoSizeHeight = true;
            this.tbQuestion.BackColor = System.Drawing.Color.Transparent;
            this.tbQuestion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbQuestion.BackgroundImage")));
            this.tbQuestion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbQuestion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbQuestion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbQuestion.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbQuestion.BorderRadius = 10;
            this.tbQuestion.BorderThickness = 1;
            this.tbQuestion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbQuestion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuestion.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbQuestion.DefaultText = "";
            this.tbQuestion.FillColor = System.Drawing.Color.White;
            this.tbQuestion.HideSelection = true;
            this.tbQuestion.IconLeft = null;
            this.tbQuestion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuestion.IconPadding = 10;
            this.tbQuestion.IconRight = null;
            this.tbQuestion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbQuestion.Lines = new string[0];
            this.tbQuestion.Location = new System.Drawing.Point(43, 337);
            this.tbQuestion.MaxLength = 32767;
            this.tbQuestion.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbQuestion.Modified = false;
            this.tbQuestion.Multiline = true;
            this.tbQuestion.Name = "tbQuestion";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuestion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbQuestion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuestion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbQuestion.OnIdleState = stateProperties8;
            this.tbQuestion.Padding = new System.Windows.Forms.Padding(3);
            this.tbQuestion.PasswordChar = '\0';
            this.tbQuestion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbQuestion.PlaceholderText = "Write question...";
            this.tbQuestion.ReadOnly = false;
            this.tbQuestion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbQuestion.SelectedText = "";
            this.tbQuestion.SelectionLength = 0;
            this.tbQuestion.SelectionStart = 0;
            this.tbQuestion.ShortcutsEnabled = true;
            this.tbQuestion.Size = new System.Drawing.Size(915, 101);
            this.tbQuestion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbQuestion.TabIndex = 69;
            this.tbQuestion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbQuestion.TextMarginBottom = 0;
            this.tbQuestion.TextMarginLeft = 3;
            this.tbQuestion.TextMarginTop = 5;
            this.tbQuestion.TextPlaceholder = "Write question...";
            this.tbQuestion.UseSystemPasswordChar = false;
            this.tbQuestion.WordWrap = true;
            // 
            // lblQuestion
            // 
            this.lblQuestion.AutoSize = true;
            this.lblQuestion.BackColor = System.Drawing.Color.Transparent;
            this.lblQuestion.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblQuestion.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.lblQuestion.Location = new System.Drawing.Point(38, 304);
            this.lblQuestion.Name = "lblQuestion";
            this.lblQuestion.Size = new System.Drawing.Size(119, 30);
            this.lblQuestion.TabIndex = 70;
            this.lblQuestion.Text = "Question 1/5";
            // 
            // tbAnswerA
            // 
            this.tbAnswerA.AcceptsReturn = false;
            this.tbAnswerA.AcceptsTab = false;
            this.tbAnswerA.AnimationSpeed = 200;
            this.tbAnswerA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAnswerA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAnswerA.AutoSizeHeight = true;
            this.tbAnswerA.BackColor = System.Drawing.Color.Transparent;
            this.tbAnswerA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAnswerA.BackgroundImage")));
            this.tbAnswerA.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAnswerA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAnswerA.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAnswerA.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAnswerA.BorderRadius = 15;
            this.tbAnswerA.BorderThickness = 1;
            this.tbAnswerA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAnswerA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerA.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbAnswerA.DefaultText = "";
            this.tbAnswerA.FillColor = System.Drawing.Color.White;
            this.tbAnswerA.HideSelection = true;
            this.tbAnswerA.IconLeft = null;
            this.tbAnswerA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerA.IconPadding = 12;
            this.tbAnswerA.IconRight = null;
            this.tbAnswerA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerA.Lines = new string[0];
            this.tbAnswerA.Location = new System.Drawing.Point(75, 461);
            this.tbAnswerA.MaxLength = 32767;
            this.tbAnswerA.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAnswerA.Modified = false;
            this.tbAnswerA.Multiline = true;
            this.tbAnswerA.Name = "tbAnswerA";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerA.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAnswerA.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerA.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerA.OnIdleState = stateProperties12;
            this.tbAnswerA.Padding = new System.Windows.Forms.Padding(3);
            this.tbAnswerA.PasswordChar = '\0';
            this.tbAnswerA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAnswerA.PlaceholderText = "Write option a..";
            this.tbAnswerA.ReadOnly = false;
            this.tbAnswerA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAnswerA.SelectedText = "";
            this.tbAnswerA.SelectionLength = 0;
            this.tbAnswerA.SelectionStart = 0;
            this.tbAnswerA.ShortcutsEnabled = true;
            this.tbAnswerA.Size = new System.Drawing.Size(270, 62);
            this.tbAnswerA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAnswerA.TabIndex = 71;
            this.tbAnswerA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAnswerA.TextMarginBottom = 0;
            this.tbAnswerA.TextMarginLeft = 3;
            this.tbAnswerA.TextMarginTop = 5;
            this.tbAnswerA.TextPlaceholder = "Write option a..";
            this.tbAnswerA.UseSystemPasswordChar = false;
            this.tbAnswerA.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Poppins SemiBold", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label4.Location = new System.Drawing.Point(37, 464);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(32, 31);
            this.label4.TabIndex = 72;
            this.label4.Text = "A.";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Poppins SemiBold", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label5.Location = new System.Drawing.Point(37, 544);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(31, 31);
            this.label5.TabIndex = 74;
            this.label5.Text = "B.";
            // 
            // tbAnswerB
            // 
            this.tbAnswerB.AcceptsReturn = false;
            this.tbAnswerB.AcceptsTab = false;
            this.tbAnswerB.AnimationSpeed = 200;
            this.tbAnswerB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAnswerB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAnswerB.AutoSizeHeight = true;
            this.tbAnswerB.BackColor = System.Drawing.Color.Transparent;
            this.tbAnswerB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAnswerB.BackgroundImage")));
            this.tbAnswerB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAnswerB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAnswerB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAnswerB.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAnswerB.BorderRadius = 15;
            this.tbAnswerB.BorderThickness = 1;
            this.tbAnswerB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAnswerB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerB.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbAnswerB.DefaultText = "";
            this.tbAnswerB.FillColor = System.Drawing.Color.White;
            this.tbAnswerB.HideSelection = true;
            this.tbAnswerB.IconLeft = null;
            this.tbAnswerB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerB.IconPadding = 12;
            this.tbAnswerB.IconRight = null;
            this.tbAnswerB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerB.Lines = new string[0];
            this.tbAnswerB.Location = new System.Drawing.Point(75, 541);
            this.tbAnswerB.MaxLength = 32767;
            this.tbAnswerB.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAnswerB.Modified = false;
            this.tbAnswerB.Multiline = true;
            this.tbAnswerB.Name = "tbAnswerB";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerB.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAnswerB.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerB.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerB.OnIdleState = stateProperties16;
            this.tbAnswerB.Padding = new System.Windows.Forms.Padding(3);
            this.tbAnswerB.PasswordChar = '\0';
            this.tbAnswerB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAnswerB.PlaceholderText = "Write option b..";
            this.tbAnswerB.ReadOnly = false;
            this.tbAnswerB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAnswerB.SelectedText = "";
            this.tbAnswerB.SelectionLength = 0;
            this.tbAnswerB.SelectionStart = 0;
            this.tbAnswerB.ShortcutsEnabled = true;
            this.tbAnswerB.Size = new System.Drawing.Size(270, 62);
            this.tbAnswerB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAnswerB.TabIndex = 73;
            this.tbAnswerB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAnswerB.TextMarginBottom = 0;
            this.tbAnswerB.TextMarginLeft = 3;
            this.tbAnswerB.TextMarginTop = 5;
            this.tbAnswerB.TextPlaceholder = "Write option b..";
            this.tbAnswerB.UseSystemPasswordChar = false;
            this.tbAnswerB.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Poppins SemiBold", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label6.Location = new System.Drawing.Point(403, 544);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(32, 31);
            this.label6.TabIndex = 78;
            this.label6.Text = "D.";
            // 
            // tbAnswerD
            // 
            this.tbAnswerD.AcceptsReturn = false;
            this.tbAnswerD.AcceptsTab = false;
            this.tbAnswerD.AnimationSpeed = 200;
            this.tbAnswerD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAnswerD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAnswerD.AutoSizeHeight = true;
            this.tbAnswerD.BackColor = System.Drawing.Color.Transparent;
            this.tbAnswerD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAnswerD.BackgroundImage")));
            this.tbAnswerD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAnswerD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAnswerD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAnswerD.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAnswerD.BorderRadius = 15;
            this.tbAnswerD.BorderThickness = 1;
            this.tbAnswerD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAnswerD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerD.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbAnswerD.DefaultText = "";
            this.tbAnswerD.FillColor = System.Drawing.Color.White;
            this.tbAnswerD.HideSelection = true;
            this.tbAnswerD.IconLeft = null;
            this.tbAnswerD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerD.IconPadding = 12;
            this.tbAnswerD.IconRight = null;
            this.tbAnswerD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerD.Lines = new string[0];
            this.tbAnswerD.Location = new System.Drawing.Point(441, 541);
            this.tbAnswerD.MaxLength = 32767;
            this.tbAnswerD.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAnswerD.Modified = false;
            this.tbAnswerD.Multiline = true;
            this.tbAnswerD.Name = "tbAnswerD";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerD.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAnswerD.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerD.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerD.OnIdleState = stateProperties20;
            this.tbAnswerD.Padding = new System.Windows.Forms.Padding(3);
            this.tbAnswerD.PasswordChar = '\0';
            this.tbAnswerD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAnswerD.PlaceholderText = "Write option d..";
            this.tbAnswerD.ReadOnly = false;
            this.tbAnswerD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAnswerD.SelectedText = "";
            this.tbAnswerD.SelectionLength = 0;
            this.tbAnswerD.SelectionStart = 0;
            this.tbAnswerD.ShortcutsEnabled = true;
            this.tbAnswerD.Size = new System.Drawing.Size(270, 62);
            this.tbAnswerD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAnswerD.TabIndex = 77;
            this.tbAnswerD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAnswerD.TextMarginBottom = 0;
            this.tbAnswerD.TextMarginLeft = 3;
            this.tbAnswerD.TextMarginTop = 5;
            this.tbAnswerD.TextPlaceholder = "Write option d..";
            this.tbAnswerD.UseSystemPasswordChar = false;
            this.tbAnswerD.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.BackColor = System.Drawing.Color.Transparent;
            this.label7.Font = new System.Drawing.Font("Poppins SemiBold", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label7.Location = new System.Drawing.Point(403, 464);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(33, 31);
            this.label7.TabIndex = 76;
            this.label7.Text = "C.";
            // 
            // tbAnswerC
            // 
            this.tbAnswerC.AcceptsReturn = false;
            this.tbAnswerC.AcceptsTab = false;
            this.tbAnswerC.AnimationSpeed = 200;
            this.tbAnswerC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAnswerC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAnswerC.AutoSizeHeight = true;
            this.tbAnswerC.BackColor = System.Drawing.Color.Transparent;
            this.tbAnswerC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAnswerC.BackgroundImage")));
            this.tbAnswerC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAnswerC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbAnswerC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAnswerC.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAnswerC.BorderRadius = 15;
            this.tbAnswerC.BorderThickness = 1;
            this.tbAnswerC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAnswerC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerC.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbAnswerC.DefaultText = "";
            this.tbAnswerC.FillColor = System.Drawing.Color.White;
            this.tbAnswerC.HideSelection = true;
            this.tbAnswerC.IconLeft = null;
            this.tbAnswerC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerC.IconPadding = 12;
            this.tbAnswerC.IconRight = null;
            this.tbAnswerC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAnswerC.Lines = new string[0];
            this.tbAnswerC.Location = new System.Drawing.Point(441, 461);
            this.tbAnswerC.MaxLength = 32767;
            this.tbAnswerC.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAnswerC.Modified = false;
            this.tbAnswerC.Multiline = true;
            this.tbAnswerC.Name = "tbAnswerC";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerC.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbAnswerC.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerC.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAnswerC.OnIdleState = stateProperties24;
            this.tbAnswerC.Padding = new System.Windows.Forms.Padding(3);
            this.tbAnswerC.PasswordChar = '\0';
            this.tbAnswerC.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAnswerC.PlaceholderText = "Write option c..";
            this.tbAnswerC.ReadOnly = false;
            this.tbAnswerC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAnswerC.SelectedText = "";
            this.tbAnswerC.SelectionLength = 0;
            this.tbAnswerC.SelectionStart = 0;
            this.tbAnswerC.ShortcutsEnabled = true;
            this.tbAnswerC.Size = new System.Drawing.Size(270, 62);
            this.tbAnswerC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbAnswerC.TabIndex = 75;
            this.tbAnswerC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAnswerC.TextMarginBottom = 0;
            this.tbAnswerC.TextMarginLeft = 3;
            this.tbAnswerC.TextMarginTop = 5;
            this.tbAnswerC.TextPlaceholder = "Write option c..";
            this.tbAnswerC.UseSystemPasswordChar = false;
            this.tbAnswerC.WordWrap = true;
            // 
            // cboAnswer
            // 
            this.cboAnswer.FormattingEnabled = true;
            this.cboAnswer.Location = new System.Drawing.Point(818, 461);
            this.cboAnswer.Margin = new System.Windows.Forms.Padding(0);
            this.cboAnswer.Name = "cboAnswer";
            this.cboAnswer.Size = new System.Drawing.Size(140, 24);
            this.cboAnswer.TabIndex = 79;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.BackColor = System.Drawing.Color.Transparent;
            this.label8.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.label8.Location = new System.Drawing.Point(741, 460);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(73, 26);
            this.label8.TabIndex = 80;
            this.label8.Text = "Answer:";
            // 
            // btnFirst
            // 
            this.btnFirst.AllowAnimations = true;
            this.btnFirst.AllowMouseEffects = true;
            this.btnFirst.AllowToggling = false;
            this.btnFirst.AnimationSpeed = 200;
            this.btnFirst.AutoGenerateColors = false;
            this.btnFirst.AutoRoundBorders = false;
            this.btnFirst.AutoSizeLeftIcon = true;
            this.btnFirst.AutoSizeRightIcon = true;
            this.btnFirst.BackColor = System.Drawing.Color.Transparent;
            this.btnFirst.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnFirst.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFirst.BackgroundImage")));
            this.btnFirst.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.ButtonText = "<<";
            this.btnFirst.ButtonTextMarginLeft = 0;
            this.btnFirst.ColorContrastOnClick = 45;
            this.btnFirst.ColorContrastOnHover = 45;
            this.btnFirst.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnFirst.CustomizableEdges = borderEdges1;
            this.btnFirst.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFirst.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirst.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnFirst.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnFirst.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFirst.Font = new System.Drawing.Font("Poppins SemiBold", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFirst.ForeColor = System.Drawing.Color.White;
            this.btnFirst.IconLeft = null;
            this.btnFirst.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFirst.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirst.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFirst.IconMarginLeft = 11;
            this.btnFirst.IconPadding = 10;
            this.btnFirst.IconRight = null;
            this.btnFirst.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFirst.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirst.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFirst.IconSize = 25;
            this.btnFirst.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnFirst.IdleBorderRadius = 0;
            this.btnFirst.IdleBorderThickness = 0;
            this.btnFirst.IdleFillColor = System.Drawing.Color.Empty;
            this.btnFirst.IdleIconLeftImage = null;
            this.btnFirst.IdleIconRightImage = null;
            this.btnFirst.IndicateFocus = false;
            this.btnFirst.Location = new System.Drawing.Point(346, 639);
            this.btnFirst.Name = "btnFirst";
            this.btnFirst.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirst.OnDisabledState.BorderRadius = 5;
            this.btnFirst.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnDisabledState.BorderThickness = 1;
            this.btnFirst.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFirst.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFirst.OnDisabledState.IconLeftImage = null;
            this.btnFirst.OnDisabledState.IconRightImage = null;
            this.btnFirst.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnFirst.onHoverState.BorderRadius = 5;
            this.btnFirst.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.onHoverState.BorderThickness = 1;
            this.btnFirst.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnFirst.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnFirst.onHoverState.IconLeftImage = null;
            this.btnFirst.onHoverState.IconRightImage = null;
            this.btnFirst.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.OnIdleState.BorderRadius = 5;
            this.btnFirst.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnIdleState.BorderThickness = 1;
            this.btnFirst.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFirst.OnIdleState.IconLeftImage = null;
            this.btnFirst.OnIdleState.IconRightImage = null;
            this.btnFirst.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnFirst.OnPressedState.BorderRadius = 5;
            this.btnFirst.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnPressedState.BorderThickness = 1;
            this.btnFirst.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnFirst.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFirst.OnPressedState.IconLeftImage = null;
            this.btnFirst.OnPressedState.IconRightImage = null;
            this.btnFirst.Size = new System.Drawing.Size(57, 42);
            this.btnFirst.TabIndex = 81;
            this.btnFirst.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFirst.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFirst.TextMarginLeft = 0;
            this.btnFirst.TextPadding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.btnFirst.UseDefaultRadiusAndThickness = true;
            this.btnFirst.Click += new System.EventHandler(this.btnFirst_Click);
            // 
            // btnPrev
            // 
            this.btnPrev.AllowAnimations = true;
            this.btnPrev.AllowMouseEffects = true;
            this.btnPrev.AllowToggling = false;
            this.btnPrev.AnimationSpeed = 200;
            this.btnPrev.AutoGenerateColors = false;
            this.btnPrev.AutoRoundBorders = false;
            this.btnPrev.AutoSizeLeftIcon = true;
            this.btnPrev.AutoSizeRightIcon = true;
            this.btnPrev.BackColor = System.Drawing.Color.Transparent;
            this.btnPrev.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnPrev.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPrev.BackgroundImage")));
            this.btnPrev.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.ButtonText = "<";
            this.btnPrev.ButtonTextMarginLeft = 0;
            this.btnPrev.ColorContrastOnClick = 45;
            this.btnPrev.ColorContrastOnHover = 45;
            this.btnPrev.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnPrev.CustomizableEdges = borderEdges2;
            this.btnPrev.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPrev.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrev.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnPrev.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnPrev.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPrev.Font = new System.Drawing.Font("Poppins SemiBold", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrev.ForeColor = System.Drawing.Color.White;
            this.btnPrev.IconLeft = null;
            this.btnPrev.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrev.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrev.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPrev.IconMarginLeft = 11;
            this.btnPrev.IconPadding = 10;
            this.btnPrev.IconRight = null;
            this.btnPrev.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrev.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrev.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPrev.IconSize = 25;
            this.btnPrev.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnPrev.IdleBorderRadius = 0;
            this.btnPrev.IdleBorderThickness = 0;
            this.btnPrev.IdleFillColor = System.Drawing.Color.Empty;
            this.btnPrev.IdleIconLeftImage = null;
            this.btnPrev.IdleIconRightImage = null;
            this.btnPrev.IndicateFocus = false;
            this.btnPrev.Location = new System.Drawing.Point(429, 639);
            this.btnPrev.Name = "btnPrev";
            this.btnPrev.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrev.OnDisabledState.BorderRadius = 5;
            this.btnPrev.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnDisabledState.BorderThickness = 1;
            this.btnPrev.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrev.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrev.OnDisabledState.IconLeftImage = null;
            this.btnPrev.OnDisabledState.IconRightImage = null;
            this.btnPrev.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrev.onHoverState.BorderRadius = 5;
            this.btnPrev.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.onHoverState.BorderThickness = 1;
            this.btnPrev.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnPrev.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrev.onHoverState.IconLeftImage = null;
            this.btnPrev.onHoverState.IconRightImage = null;
            this.btnPrev.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.OnIdleState.BorderRadius = 5;
            this.btnPrev.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnIdleState.BorderThickness = 1;
            this.btnPrev.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPrev.OnIdleState.IconLeftImage = null;
            this.btnPrev.OnIdleState.IconRightImage = null;
            this.btnPrev.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrev.OnPressedState.BorderRadius = 5;
            this.btnPrev.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnPressedState.BorderThickness = 1;
            this.btnPrev.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnPrev.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPrev.OnPressedState.IconLeftImage = null;
            this.btnPrev.OnPressedState.IconRightImage = null;
            this.btnPrev.Size = new System.Drawing.Size(57, 42);
            this.btnPrev.TabIndex = 82;
            this.btnPrev.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrev.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPrev.TextMarginLeft = 0;
            this.btnPrev.TextPadding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.btnPrev.UseDefaultRadiusAndThickness = true;
            this.btnPrev.Click += new System.EventHandler(this.btnPrev_Click);
            // 
            // btnLast
            // 
            this.btnLast.AllowAnimations = true;
            this.btnLast.AllowMouseEffects = true;
            this.btnLast.AllowToggling = false;
            this.btnLast.AnimationSpeed = 200;
            this.btnLast.AutoGenerateColors = false;
            this.btnLast.AutoRoundBorders = false;
            this.btnLast.AutoSizeLeftIcon = true;
            this.btnLast.AutoSizeRightIcon = true;
            this.btnLast.BackColor = System.Drawing.Color.Transparent;
            this.btnLast.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLast.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLast.BackgroundImage")));
            this.btnLast.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.ButtonText = ">>";
            this.btnLast.ButtonTextMarginLeft = 0;
            this.btnLast.ColorContrastOnClick = 45;
            this.btnLast.ColorContrastOnHover = 45;
            this.btnLast.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLast.CustomizableEdges = borderEdges3;
            this.btnLast.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLast.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLast.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLast.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLast.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLast.Font = new System.Drawing.Font("Poppins SemiBold", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLast.ForeColor = System.Drawing.Color.White;
            this.btnLast.IconLeft = null;
            this.btnLast.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLast.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLast.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLast.IconMarginLeft = 11;
            this.btnLast.IconPadding = 10;
            this.btnLast.IconRight = null;
            this.btnLast.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLast.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLast.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLast.IconSize = 25;
            this.btnLast.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLast.IdleBorderRadius = 0;
            this.btnLast.IdleBorderThickness = 0;
            this.btnLast.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLast.IdleIconLeftImage = null;
            this.btnLast.IdleIconRightImage = null;
            this.btnLast.IndicateFocus = false;
            this.btnLast.Location = new System.Drawing.Point(601, 639);
            this.btnLast.Name = "btnLast";
            this.btnLast.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLast.OnDisabledState.BorderRadius = 5;
            this.btnLast.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnDisabledState.BorderThickness = 1;
            this.btnLast.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLast.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLast.OnDisabledState.IconLeftImage = null;
            this.btnLast.OnDisabledState.IconRightImage = null;
            this.btnLast.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLast.onHoverState.BorderRadius = 5;
            this.btnLast.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.onHoverState.BorderThickness = 1;
            this.btnLast.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnLast.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLast.onHoverState.IconLeftImage = null;
            this.btnLast.onHoverState.IconRightImage = null;
            this.btnLast.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.OnIdleState.BorderRadius = 5;
            this.btnLast.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnIdleState.BorderThickness = 1;
            this.btnLast.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLast.OnIdleState.IconLeftImage = null;
            this.btnLast.OnIdleState.IconRightImage = null;
            this.btnLast.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLast.OnPressedState.BorderRadius = 5;
            this.btnLast.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnPressedState.BorderThickness = 1;
            this.btnLast.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLast.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLast.OnPressedState.IconLeftImage = null;
            this.btnLast.OnPressedState.IconRightImage = null;
            this.btnLast.Size = new System.Drawing.Size(57, 42);
            this.btnLast.TabIndex = 84;
            this.btnLast.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLast.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLast.TextMarginLeft = 0;
            this.btnLast.TextPadding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.btnLast.UseDefaultRadiusAndThickness = true;
            this.btnLast.Click += new System.EventHandler(this.btnLast_Click);
            // 
            // btnNext
            // 
            this.btnNext.AllowAnimations = true;
            this.btnNext.AllowMouseEffects = true;
            this.btnNext.AllowToggling = false;
            this.btnNext.AnimationSpeed = 200;
            this.btnNext.AutoGenerateColors = false;
            this.btnNext.AutoRoundBorders = false;
            this.btnNext.AutoSizeLeftIcon = true;
            this.btnNext.AutoSizeRightIcon = true;
            this.btnNext.BackColor = System.Drawing.Color.Transparent;
            this.btnNext.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnNext.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNext.BackgroundImage")));
            this.btnNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.ButtonText = ">";
            this.btnNext.ButtonTextMarginLeft = 0;
            this.btnNext.ColorContrastOnClick = 45;
            this.btnNext.ColorContrastOnHover = 45;
            this.btnNext.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnNext.CustomizableEdges = borderEdges4;
            this.btnNext.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNext.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnNext.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNext.Font = new System.Drawing.Font("Poppins SemiBold", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNext.ForeColor = System.Drawing.Color.White;
            this.btnNext.IconLeft = null;
            this.btnNext.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNext.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNext.IconMarginLeft = 11;
            this.btnNext.IconPadding = 10;
            this.btnNext.IconRight = null;
            this.btnNext.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNext.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNext.IconSize = 25;
            this.btnNext.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnNext.IdleBorderRadius = 0;
            this.btnNext.IdleBorderThickness = 0;
            this.btnNext.IdleFillColor = System.Drawing.Color.Empty;
            this.btnNext.IdleIconLeftImage = null;
            this.btnNext.IdleIconRightImage = null;
            this.btnNext.IndicateFocus = false;
            this.btnNext.Location = new System.Drawing.Point(518, 639);
            this.btnNext.Name = "btnNext";
            this.btnNext.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.OnDisabledState.BorderRadius = 5;
            this.btnNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnDisabledState.BorderThickness = 1;
            this.btnNext.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNext.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNext.OnDisabledState.IconLeftImage = null;
            this.btnNext.OnDisabledState.IconRightImage = null;
            this.btnNext.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.BorderRadius = 5;
            this.btnNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.onHoverState.BorderThickness = 1;
            this.btnNext.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnNext.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.IconLeftImage = null;
            this.btnNext.onHoverState.IconRightImage = null;
            this.btnNext.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.OnIdleState.BorderRadius = 5;
            this.btnNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnIdleState.BorderThickness = 1;
            this.btnNext.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnIdleState.IconLeftImage = null;
            this.btnNext.OnIdleState.IconRightImage = null;
            this.btnNext.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.OnPressedState.BorderRadius = 5;
            this.btnNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnPressedState.BorderThickness = 1;
            this.btnNext.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnNext.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnPressedState.IconLeftImage = null;
            this.btnNext.OnPressedState.IconRightImage = null;
            this.btnNext.Size = new System.Drawing.Size(57, 42);
            this.btnNext.TabIndex = 83;
            this.btnNext.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNext.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNext.TextMarginLeft = 0;
            this.btnNext.TextPadding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.btnNext.UseDefaultRadiusAndThickness = true;
            this.btnNext.Click += new System.EventHandler(this.btnNext_Click);
            // 
            // btnUpdate
            // 
            this.btnUpdate.AllowAnimations = true;
            this.btnUpdate.AllowMouseEffects = true;
            this.btnUpdate.AllowToggling = false;
            this.btnUpdate.AnimationSpeed = 200;
            this.btnUpdate.AutoGenerateColors = false;
            this.btnUpdate.AutoRoundBorders = false;
            this.btnUpdate.AutoSizeLeftIcon = true;
            this.btnUpdate.AutoSizeRightIcon = true;
            this.btnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.ButtonText = "Update";
            this.btnUpdate.ButtonTextMarginLeft = 0;
            this.btnUpdate.ColorContrastOnClick = 45;
            this.btnUpdate.ColorContrastOnHover = 45;
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnUpdate.CustomizableEdges = borderEdges5;
            this.btnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUpdate.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdate.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.IconLeft = null;
            this.btnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpdate.IconMarginLeft = 11;
            this.btnUpdate.IconPadding = 10;
            this.btnUpdate.IconRight = null;
            this.btnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdate.IconSize = 25;
            this.btnUpdate.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUpdate.IdleBorderRadius = 0;
            this.btnUpdate.IdleBorderThickness = 0;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUpdate.IdleIconLeftImage = null;
            this.btnUpdate.IdleIconRightImage = null;
            this.btnUpdate.IndicateFocus = false;
            this.btnUpdate.Location = new System.Drawing.Point(341, 702);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.OnDisabledState.BorderRadius = 35;
            this.btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnDisabledState.BorderThickness = 1;
            this.btnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.OnDisabledState.IconLeftImage = null;
            this.btnUpdate.OnDisabledState.IconRightImage = null;
            this.btnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.onHoverState.BorderRadius = 35;
            this.btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.onHoverState.BorderThickness = 1;
            this.btnUpdate.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnUpdate.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.onHoverState.IconLeftImage = null;
            this.btnUpdate.onHoverState.IconRightImage = null;
            this.btnUpdate.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.OnIdleState.BorderRadius = 35;
            this.btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnIdleState.BorderThickness = 1;
            this.btnUpdate.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnIdleState.IconLeftImage = null;
            this.btnUpdate.OnIdleState.IconRightImage = null;
            this.btnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.OnPressedState.BorderRadius = 35;
            this.btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnPressedState.BorderThickness = 1;
            this.btnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnPressedState.IconLeftImage = null;
            this.btnUpdate.OnPressedState.IconRightImage = null;
            this.btnUpdate.Size = new System.Drawing.Size(317, 42);
            this.btnUpdate.TabIndex = 85;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdate.TextMarginLeft = 0;
            this.btnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdate.UseDefaultRadiusAndThickness = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges6;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.Transparent;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleBorderRadius = 0;
            this.btnCancel.IdleBorderThickness = 0;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(518, 702);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 35;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.onHoverState.BorderRadius = 35;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnIdleState.BorderRadius = 35;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnPressedState.BorderRadius = 35;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(145, 42);
            this.btnCancel.TabIndex = 87;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges7;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = null;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSave.IdleBorderRadius = 0;
            this.btnSave.IdleBorderThickness = 0;
            this.btnSave.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(341, 702);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 35;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 35;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 35;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.OnPressedState.BorderRadius = 35;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(145, 42);
            this.btnSave.TabIndex = 86;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // FormViewCase
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1004, 800);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnLast);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnPrev);
            this.Controls.Add(this.btnFirst);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.cboAnswer);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.tbAnswerD);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.tbAnswerC);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.tbAnswerB);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.tbAnswerA);
            this.Controls.Add(this.lblQuestion);
            this.Controls.Add(this.tbQuestion);
            this.Controls.Add(this.dgvData);
            this.Controls.Add(this.tbSearch);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormViewCase";
            this.Text = "FormViewCase";
            this.Load += new System.EventHandler(this.FormViewCase_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataGridView dgvData;
        private Bunifu.UI.WinForms.BunifuTextBox tbSearch;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox tbQuestion;
        private System.Windows.Forms.Label lblQuestion;
        private Bunifu.UI.WinForms.BunifuTextBox tbAnswerA;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox tbAnswerB;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox tbAnswerD;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox tbAnswerC;
        private System.Windows.Forms.ComboBox cboAnswer;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFirst;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPrev;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLast;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNext;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
    }
}